spring:
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: paymentConfirmation:com.younes.payment.notification.PaymentNotificationRequest
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8055