package com.younes.order.models;

import java.util.List;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * OrderRequest
 *
 * Two things a client must never supply are absent by design:
 * <ul>
 *   <li>{@code id} — the identifier is generated by the database, so a client cannot
 *       submit an existing id and overwrite that order on save.</li>
 *   <li>{@code amount} — the total is computed server-side from the product catalogue,
 *       so a client cannot order a 999.99 laptop for 0.01.</li>
 * </ul>
 *
 * {@code customerId} is also not accepted here: it is resolved from the caller's JWT,
 * otherwise any authenticated user could place an order against another customer's id.
 */
@Data
public class OrderRequest {
    @NotBlank(message = "The order reference is required !")
    String reference;
    @NotNull(message = "Payement methode is required !")
    PaymentMethod paymentMethod;
    @NotEmpty(message = "You have to order one or more products")
    @Valid
    List<PurchaseRequest> products;
}