package com.younes.eccomerc.product;

import java.math.BigDecimal;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.Getter;
import lombok.Setter;

/**
 * ProductRequest
 *
 * There is deliberately no id field: the identifier is generated by the database, so a
 * client cannot submit an existing id and overwrite another product on save.
 */
@Getter
@Setter
public class ProductRequest {

    @NotNull(message = "The product name is required !")
    String name;
    @NotNull(message = "The product descreption is required !")
    String description;
    @PositiveOrZero(message = "The product quantity should be positive or zero !")
    double availableQuantity;
    @NotNull(message = "The product price is required !")
    @Positive(message = "The product price should be positive !")
    BigDecimal price;
    @NotNull(message = "The product category is required  !")
    Integer categoryId;
}