package com.younes.order.payment;

import java.math.BigDecimal;

import com.younes.order.models.PaymentMethod;
import com.younes.order.models.customer.CustomerResponse;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * PaymentRequest
 *
 * There is deliberately no id field: the payment identifier is generated by the
 * database. Previously a non-null id was mapped onto the entity primary key, so a
 * request could update an existing payment row instead of creating one.
 */
@Getter
@AllArgsConstructor
public class PaymentRequest {
    private BigDecimal amount;
    private PaymentMethod paymentMethod;
    Integer orderId;
    String orderReference;
    CustomerResponse customer;
}